# Generated by Django 4.1.7 on 2023-04-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, null=True)),
                ('lastname', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('band', models.CharField(max_length=255, null=True)),
                ('dateOfBirth', models.DateField(null=True)),
                ('pp', models.BinaryField(null=True)),
                ('coverphoto', models.BinaryField(null=True)),
                ('bio', models.CharField(max_length=150, null=True)),
                ('story', models.BinaryField(null=True)),
                ('musicGenre', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'artists',
            },
        ),
    ]
